---
title: "Example Health Policy Dissertation"
author: "Emma Cormack"
date: "2025-10-03"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is example research project following the acceptance of my undergraduate dissertation. This project demonstrates my ability to design and undertake quantitative research. The analysis used was an ordered logistic regression model. Example data was used (generated by ChatGPT) in order to protect my original results and participant data. My final dissertation received an A grade from the University of Glasgow.

This project includes:
1. An outline of my research design.
2. Results of the example survey data.
3. Analysis of the survey data using an ordered logistic regression model.
4. Interpretation of these results. 

## Research Design

**Dissertation Aim: To evaluate the extent to which the aims and outcomes of the 2018 General Medical Services Contract facilitate patient-centred care in remote and rural general practices of Scotland.**
The 2018 General Medical Services Contract (The Contract) is a topical and influential piece of legislation in Scotland's NHS. By exploring the extent to which it is patient-centred, it was possible to discuss a factor of its quality as a policy.

**Research Question: What factors influence patient satisfaction with general practices in remote and rural areas of Scotland?**

This research question represented the quantitative research section of this dissertation, and appeared alongside two other research questions which allowed for qualitative research and a critique of the policy.

**Methods:** 
A sample of the remote and rural population of Grampian was questionned using an online questionnaire prepared in Qualtrics, delivered using Facebook community groups. Grampian was used as a case study to represent the larger population of remote and rural Scotland to save time and costs. The study uses the Scottish Government 6-fold classification of urban and rural places.

To analyse the questionnaire data an ordinal logistic regression model was administered using R software. The model fit was tested with the McFadden R2 and the Proportional Regression Assumption, which identifies whether the model results can be relied upon. Multicollinearity was tested using multi correspondence analysis, a method of graphic categorical variables to check for similarities. Odds ratios were used to interpret the results of the model. 

The example data was generated using this prompt in ChatGPT:
"Generate example data in excel with these concepts and corresponding variable codes: Patient satisfaction PATSAT Satisfaction with GP communication GPCOMS Travel time to GP practice TRAVEL Whether or not served by MDT staff MDTSTAFF Appointment location APPTLOC GP practice closed or combined with another practice CLOSURE Appointment timeliness TIMELINESS Age AGE GP reception staff helpfulness STAFFCOMS Number of visits to surgery in previous year NVISITS Extent to which provider treatment was effective EFFICACY Expectations for last appointment EXPECTATION Years with GP practice YRSWGP Gender GENDER Whether they have a preferred GP FAVGP Health status HEALTHSTAT How often they see preferred GP SEEFAVGP Ethnicity ETHNICITY Extent to which treated with compassion and understanding COMPASSION How often they see the same GP SAMEGP SIMD SIMD Connectivity CONNECT Urban/RR classification RRCLASS. SIMD should contain values 1-5. Urban/RR classification should contain values 1-6. I would like the results to be have a trend. For example, older people are more likely to have more GP visits in the previous year. Results should be intuitive but naturally contain idiosyncracies. Most variables should be Likert scales of 5 e.g. Very dissatisfied, quite dissatisfied, neither satisfied nor dissatisfied, quite satisfied, very satisfied, and all being from 1 (least) to 5 (most). I would like to include around 200 participants (rows) and all variables should appear as column headers. All information should be inputted in British English."


